/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'rp2040_example' 
 * Target:  'Pico' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "rp2040.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* RaspberryPi::Device:Pico SDK@1.5.1 */
#define RTE_Device_Pico_SDK     /* Device Pico-SDK */
/* RaspberryPi::Device:Startup&C Startup@1.1.0 */
#define RTE_Device_Startup_RP2040    /* Device Startup for RP2040 */


#endif /* RTE_COMPONENTS_H */
